### ISSUE TITLE
What Camera Module are you using?

### ISSUE THREAD

**Issue by Zeit42** [masato-ka/object-deteciton-sample#1]
I've cloned the project and imported it to my Android Studio. I then deployed it to my Raspberry Pi 3 B Board. However, I only see a black screen. The App didn't crash or anything, it just seems that it can't fetch the Camera Data properly.

I'm using a NoIR Camera v2.1 plugging in via the same slot that the PiCam goes into.

**Comment by masato-ka** [comment]
Using normal raspberry pi camera v2
I did not testing with NoIR.
https://www.raspberrypi.org/products/camera-module-v2/

**Comment by lubangray5** [comment]
when i  try to run  the app  it shows error
Cannot expand ZIP 'C:\Users\R.C. Lubang\Desktop\AT\object-deteciton-sample-master\app\build\downloads\coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.zip' as it does not exist.

**Comment by inakaaay** [comment]
i used camera v2 but it doesnt show anything or just a black screen when i run your code. here is the logcat
![image](https://user-images.githubusercontent.com/40930782/56630669-b7fc6b00-6684-11e9-807f-46ea5901f9aa.png)

**Comment by masato-ka** [comment]
I update repository.
